site_name: BaaS
pages:
  - Конфигурация:
      - Введение: 'configuration/intro.md'
      - Глоссарий: 'configuration/glossary.md'
      - Туториал: 'configuration/tutorial.md'
  - О проекте: 'about.md'
